name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

concurrency:
  group: ${{github.repository}}-${{github.ref_name}}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Cache tools
      uses: actions/cache@v4
      with:
        path: tools
        key: ${{ runner.os }}-tools-${{ hashFiles('tools/**') }}
        restore-keys: |
          ${{ runner.os }}-tools-

    - name: Retrieve required files
      run: curl -L "https://drive.google.com/uc?export=download&id=1q4wA2GaeALgVH4e-lgyos0MA6nWNRWRk" > baserom.jp.z64

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sm64

    - name: Run the Docker image
      run: docker run --rm --mount type=bind,source="$(pwd)",destination=/sm64 sm64 bash makecontinuous.sh ${{github.event.repository.name}} ${{github.ref_name}}

    # --- ファイルサイズチェック ステップ ---
    - name: Validate build artifacts
      run: |
        FILES=(
          "${{github.event.repository.name}}-${{github.ref_name}}.bps"
        )
        
        THRESHOLD=1024 # 1KB
        
        for FILE in "${FILES[@]}"; do
          if [ ! -f "$FILE" ]; then
            echo "::error::File not found: $FILE"
            exit 1
          fi
          
          SIZE=$(stat -c%s "$FILE")
          if [ "$SIZE" -lt "$THRESHOLD" ]; then
            echo "::error::Build artifact $FILE is too small ($SIZE bytes). Expected at least ${THRESHOLD} bytes."
            exit 1
          fi
          echo "Success: $FILE is $SIZE bytes."
        done

    - name: Push build to GitHub releases
      uses: docker://ghcr.io/mini-bomba/create-github-release:main
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        name: "Continuous Pre-releases"
        tag: "continuous"
        body: |
            This automatic pre-release is built from commit ${{github.sha}} and was triggered by @${{github.actor}}
            [Github Actions workflow run that built this pre-release](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
            
            Builds from other branches are also available under this pre-release. The latest build is `${{github.event.repository.name}}-${{github.ref_name}}.bps`.
            
            Please note that there may be breaking changes in these builds, and that they aren't recommended for regular play sessions.
            
            Commit message from latest build:
            ${{github.event.head_commit.message}}
        files: |
          ${{github.event.repository.name}}-${{github.ref_name}}.bps
        clear_attachments: false
        prerelease: true
